version: '2'
services:
  calificaciones-api:
    container_name: calificaciones2-api
    restart: always
    image: ualmtorres/phalcon-apache-ubuntu
    ports:
      - "8079:80"
    volumes:
      - ./api:/var/www/html

  calificaciones-front:
    container_name: calificaciones2-frontend
    restart: always
    image: php:7.2-apache
    ports:
      - "8087:80"
    volumes:
      - ./frontend:/var/www/html